### ISSUE TITLE
完整的模型

### ISSUE THREAD

**Issue by lin-ovvo1111** [LiLisaZhi/STADE-CDNet#1]
作者您好，在models.networks.py文件，关于您模型后半段好想并没有体现在代码上，只是单次的结果，融合四个阶段的D1、D2、D3、D4似乎并没有，还是说完整模型在其他代码里，看的有点模糊，如果有空请指点一二，求完整代码！
![QQ图片20240313203424](https://github.com/LiLisaZhi/STADE-CDNet/assets/68372645/7fbc1ce3-fdab-4237-869a-fa64369702f6)

**Comment by LiLisaZhi** [comment]
您好,已经邮件发给您.
